# Generated by Django 5.1.6 on 2025-05-13 13:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('employees', '0002_employee_id_card_photo_employee_photo'),
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('interview_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('feedback', models.TextField()),
                ('rating', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_archived', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_posting.job_posting')),
            ],
            options={
                'db_table': 'interviews',
            },
        ),
    ]
