# Generated by Django 5.1.6 on 2025-05-05 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('onboarding_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('offer_details', models.JSONField(default=dict)),
                ('contract_details', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_posting.job_posting')),
            ],
            options={
                'db_table': 'onboarding',
            },
        ),
    ]
