# Generated by Django 5.1.6 on 2025-05-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime_Requests',
            fields=[
                ('request_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=10, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'db_table': 'overtime_requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
