# Generated by Django 5.1.6 on 2025-04-19 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('resume_path', models.TextField()),
                ('application_status', models.CharField(choices=[('Applied', 'Applied'), ('Reviewed', 'Reviewed'), ('Interviewed', 'Interviewed'), ('Offered', 'Offered'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('interview_details', models.JSONField(blank=True, default=dict)),
                ('offer_details', models.JSONField(blank=True, default=dict)),
                ('contract_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='job_posting.job_posting')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'candidates',
            },
        ),
    ]
