# Generated by Django 5.1.7 on 2025-04-05 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='typical_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the position in days.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
