# Generated by Django 5.1.7 on 2025-04-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_alter_position_typical_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='typical_duration_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
