# Generated by Django 5.1.6 on 2025-04-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('salary_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('regular', 'Regular'), ('contractual', 'Contractual'), ('seasonal', 'Seasonal')], default='regular', max_length=20)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_salary',
                'unique_together': {('employee_id', 'effective_date')},
            },
        ),
    ]
