# Generated by Django 5.1.7 on 2025-04-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar_Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('is_workday', models.BooleanField()),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
                ('holiday_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Calendar Dates',
                'verbose_name_plural': 'Calendar Dates',
                'db_table': 'calendar_dates',
            },
        ),
    ]
