# Generated by Django 5.1.7 on 2025-04-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar_date',
            name='holiday_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
