# Generated by Django 5.1.7 on 2025-04-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceAllocation',
            fields=[
                ('allocation_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('requesting_dept_id', models.CharField(max_length=255)),
                ('current_dept_id', models.CharField(max_length=255)),
                ('required_skills', models.TextField()),
                ('task_description', models.TextField()),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review')], default='Pending', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Active', 'Active'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_allocations', to='employees.employee')),
                ('hr_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_allocations', to='employees.employee')),
            ],
            options={
                'db_table': 'workforce_allocation',
            },
        ),
    ]
