# Generated by Django 5.1.6 on 2025-04-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce_allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforce_allocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
