# Generated by Django 5.1.6 on 2025-04-04 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('performance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('review_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('immediate_superior', models.ForeignKey(blank=True, db_column='immediate_superior_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_performances', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_performance',
            },
        ),
    ]
