# Generated by Django 5.1.6 on 2025-04-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_alter_job_posting_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job_posting',
            table='job_posting',
        ),
    ]
