# Generated by Django 5.1.6 on 2025-04-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSuperior',
            fields=[
                ('dept_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('superior_job_title', models.CharField(max_length=100)),
                ('hierarchy_level', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'department_superiors',
                'unique_together': {('dept_id', 'superior_job_title')},
            },
        ),
    ]
