# Generated by Django 5.1.6 on 2025-05-13 13:46

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_id_cards'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos', validators=[employees.models.validate_image]),
        ),
    ]
