# Generated by Django 5.1.6 on 2025-05-15 09:01

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_id_card_photo_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='employee_photos', validators=[employees.models.validate_image]),
        ),
    ]
