# Generated by Django 5.1.6 on 2025-04-13 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0003_department_change_reason_and_more'),
        ('positions', '0002_position_change_reason_historicalposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Superior',
            fields=[
                ('dept_superior_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('hierarchy_level', models.PositiveIntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('position', models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.CASCADE, to='positions.position')),
            ],
            options={
                'verbose_name': 'Department Superiors',
                'verbose_name_plural': 'Department Superiors',
                'db_table': 'department_superiors',
            },
        ),
    ]
