# Generated by Django 5.1.6 on 2025-04-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Superior',
            fields=[
                ('dept_superior_id', models.CharField(default='', editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('hierarchy_level', models.PositiveIntegerField()),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Department Superiors',
                'verbose_name_plural': 'Department Superiors',
                'db_table': 'department_superiors',
                'managed': False,
            },
        ),
    ]
