# Generated by Django 5.1.6 on 2025-04-13 09:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_superiors', '0001_initial'),
        ('departments', '0003_department_change_reason_and_more'),
        ('employees', '0002_employee_change_reason_historicalemployee'),
        ('positions', '0002_position_change_reason_historicalposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department_superior',
            name='change_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department_superior',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.CreateModel(
            name='HistoricalDepartment_Superior',
            fields=[
                ('dept_superior_id', models.CharField(db_index=True, editable=False, max_length=50)),
                ('hierarchy_level', models.PositiveIntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dept', models.ForeignKey(blank=True, db_column='dept_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, db_column='position_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='positions.position')),
            ],
            options={
                'verbose_name': 'historical Department Superiors',
                'verbose_name_plural': 'historical Department Superiors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
