# Generated by Django 5.1.6 on 2025-04-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Leave_Balance',
            fields=[
                ('balance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=2025)),
                ('sick_leave_remaining', models.IntegerField(default=15)),
                ('vacation_leave_remaining', models.IntegerField(default=15)),
                ('maternity_leave_remaining', models.IntegerField(default=105)),
                ('paternity_leave_remaining', models.IntegerField(default=7)),
                ('solo_parent_leave_remaining', models.IntegerField(default=7)),
                ('unpaid_leave_taken', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Employee Leave Balance',
                'verbose_name_plural': 'Employee Leave Balances',
                'db_table': 'employee_leave_balances',
            },
        ),
    ]
