# Generated by Django 5.1.6 on 2025-04-16 14:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('employment_type', models.CharField(max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('holiday_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('thirteenth_month_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sss_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('philhealth_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pagibig_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('absent_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('undertime_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Finalized', 'Finalized'), ('Locked', 'Locked')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payroll',
                'db_table': 'payroll',
            },
        ),
    ]
