# Generated by Django 5.1.6 on 2025-04-16 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_superiors', '0001_initial'),
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Leave_Request',
            fields=[
                ('leave_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('Sick', 'Sick'), ('Vacation', 'Vacation'), ('Emergency', 'Emergency')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('is_paid', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dept', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('immediate_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='department_superiors.department_superior')),
                ('management_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_approved_leaves', to='department_superiors.department_superior')),
            ],
            options={
                'verbose_name': 'Employee Leave Request',
                'verbose_name_plural': 'Employee Leave Requests',
                'db_table': 'leave_requests',
            },
        ),
    ]
