# Generated by Django 5.1.6 on 2025-04-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_leave_request',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
