# Generated by Django 5.1.6 on 2025-04-13 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_leave_request',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
