# Generated by Django 5.1.6 on 2025-04-13 04:13

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_superiors', '0002_department_superior_change_reason_and_more'),
        ('departments', '0003_department_change_reason_and_more'),
        ('employee_leave_requests', '0003_employee_leave_request_created_at'),
        ('employees', '0002_employee_change_reason_historicalemployee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_leave_request',
            name='change_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalEmployee_Leave_Request',
            fields=[
                ('leave_id', models.CharField(db_index=True, max_length=255)),
                ('leave_type', models.CharField(choices=[('Sick', 'Sick'), ('Vacation', 'Vacation'), ('Emergency', 'Emergency')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('is_paid', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dept', models.ForeignKey(blank=True, db_column='dept_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('immediate_superior', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='department_superiors.department_superior')),
                ('management_approval', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='department_superiors.department_superior')),
            ],
            options={
                'verbose_name': 'historical Employee Leave Request',
                'verbose_name_plural': 'historical Employee Leave Requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
