# Generated by Django 5.1.6 on 2025-04-15 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('resignation_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('notice_period_days', models.IntegerField()),
                ('hr_approver_id', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_status', models.CharField(default='Pending', max_length=20)),
                ('clearance_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
