# Generated by Django 5.1.7 on 2025-04-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_change_reason_historicalemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Salary',
            fields=[
                ('salary_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Salary',
                'verbose_name_plural': 'Employee Salary',
                'db_table': 'employee_salary',
                'managed': True,
                'unique_together': {('employee', 'effective_date')},
            },
        ),
    ]
