# Generated by Django 5.1.7 on 2025-04-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
