# Generated by Django 5.1.6 on 2025-04-19 23:23

import attendance_tracking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_dates', '0001_initial'),
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Tracking',
            fields=[
                ('attendance_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Clocked Out', 'Clocked Out'), ('Absent', 'Absent'), ('On Leave', 'On Leave'), ('Late', 'Late'), ('Half Day', 'Half Day')], default='Present', max_length=20)),
                ('late_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('undertime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_holiday', models.BooleanField(default=False)),
                ('holiday_type', models.CharField(blank=True, max_length=20, null=True)),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_dates.calendar_date')),
                ('employee', models.ForeignKey(default=attendance_tracking.models.Attendance_Tracking.get_default_employee, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance Tracking',
                'verbose_name_plural': 'Attendance Tracking',
                'db_table': 'attendance_tracking',
            },
        ),
    ]
