# Generated by Django 5.1.7 on 2025-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'departments',
                'indexes': [models.Index(condition=models.Q(('is_archived', False)), fields=['dept_name'], name='unique_active_dept_name')],
            },
        ),
    ]
