# Generated by Django 5.1.7 on 2025-04-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_historicaldepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='change_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='change_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
